baseURL = "https://Ahmad-Fermion.github.io/"
languageCode = "en-us"
title = "Ahmadreza Rajabi"
theme = "barks"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"

[params.head]
    author = ""
    custom_css = ""
    description = "Ph.D. Candidate in Computational Chemistry<br>Electronic Structure Theory, Quantum Computing, Materials Science"
    keywords = ["computational chemistry", "drug discovery", "quantum computing", "materials science", "f-block chemistry"]

[params.navigation]
    show_navigation = true

[params.footer]
    show_footer = true

[params.typography]
    title_font = "Bree Serif"
    body_font = "Source Sans Pro"

[params.colors]
    theme_color = "#2c3e50"
    background_color = "#f9f9f9"
    text_color = "#333333"
    link_color = "#3498db"

[params.social]
    [params.social.email]
        name = "E-Mail"
        class = "fas fa-envelope"
        url = "mailto:arajabis@uci.edu"
        weight = 1
    [params.social.github]
        name = "GitHub"
        class = "fab fa-github"
        url = "https://github.com/Ahmad-Fermion"
        weight = 2
    [params.social.google_scholar]
        name = "Google Scholar"
        class = "ai ai-google-scholar-square"
        url = "https://scholar.google.com/citations?hl=en&user=dhGYmhQAAAAJ"
        weight = 3

[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 1
[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 2
[[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 3
[[menu.main]]
    name = "Media"
    url = "/media/"
    weight = 4
[[menu.main]]
    name = "Photos"
    url = "/photos/"
    weight = 5
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6
[[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 7
